pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                dir("${env.WORKSPACE}/customer-servicd"){
                sh 'mvn -B -DskipTests clean package'
                }
            }
        }
    }
        stage('Test') {
                    steps {
                    dir("${env.WORKSPACE}/customer-servicd") {
                        sh 'mvn test'
                        }
                    }
                    post {
                        always {
                            junit 'target/surefire-reports/*.xml'
                        }
                    }
                }
        stage('Deliver') {
                    steps {
                        dir("${env.WORKSPACE}/customer-servicd") {
                        sh './jenkins/scripts/deliver.sh'
                        }
                    }
                }
                }
}